DBMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.generic.base import TemplateView


urlpatterns = [
    url('^$', views.index, name='index'),
    url('^admin/', admin.site.urls),
    url('^studentportal/', include('studentportal.urls')),
    url('^facultyportal/', include('facultyportal.urls')),
    url('^dean_staff_office/',include('dean_staff_office.urls'))
]

studentportal/urls.py
from . import views
from django.conf.urls import url


app_name = 'studentportal'

urlpatterns = [
	url('^$', views.index, name='index'),
	url('^view_grades', views.view_grades, name='view_grades'),
	url('^logout/$', views.logout_user, name='logout'),
	url('^home/$', views.home, name='home'),
	url('^login/$', views.login_user, name='login'),
	url('^register_courses/$', views.register_courses, name='register_courses'),
	url('^add_course_batch/$', views.add_course_batch, name='add_course_batch'),
	url('^add_course_other_batch/$', views.add_course_other_batch, name='add_course_other_batch'),
	url('^delete_reg_course', views.delete_reg_course, name='delete_reg_course'),
	url('^delete_tokened_course', views.delete_tokened_course, name='delete_tokened_course')
]

studentportal/models.py
from __future__ import unicode_literals
from django import forms
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime
# Create your models here.
now = datetime.datetime.now()
class department(models.Model):
	dept_id=models.IntegerField()
	dept_name=models.CharField(max_length=25)
	def __str__(self):
   		return self.dept_name

class batch(models.Model):
	dept=models.ForeignKey(department,on_delete=models.CASCADE)
	year=models.IntegerField(validators=[MaxValueValidator(4),MinValueValidator(1)])
	def __str__(self):
		return self.dept.dept_name + " " + str(self.year)


class student(models.Model):
	student_id=models.CharField(max_length=25,primary_key=True)
	name=models.CharField(max_length=40)
	dept_id=models.ForeignKey(department,on_delete=models.CASCADE)
	cgpa=models.DecimalField(decimal_places=2,max_digits=10,default=0)
	curr_registered_credits=models.IntegerField(default=0)
	max_credit=models.DecimalField(default=24, max_digits=10, decimal_places=2)
	total_credits=models.DecimalField(default=0, max_digits=10, decimal_places=2)
	current_year=models.IntegerField(validators=[MaxValueValidator(4),MinValueValidator(1)],default=1)
	current_sem=models.IntegerField(validators=[MaxValueValidator(2),MinValueValidator(1)],default=1)
	password=models.CharField(max_length=50,default="abcdefgh")
	student_email=models.CharField(max_length=100, default="")	
	def __str__(self):
   		return self.name


class course(models.Model):
	course_id=models.CharField(max_length=25,primary_key=True)
	credit_struct=models.CharField(max_length=25)
	title=models.CharField(max_length=40)
	dept_id=models.ForeignKey(department,on_delete=models.CASCADE)
	def __str__(self):
   		return self.title


class faculty(models.Model):
	faculty_id=models.CharField(max_length=25,primary_key=True)
	name=models.CharField(max_length=40)
	dept_id=models.ForeignKey(department,on_delete=models.CASCADE)
	password=models.CharField(max_length=12, default="abcdefgh")
	email_id=models.EmailField()
	def __str__(self):
   		return self.name

class dean_staff_office(models.Model):
	staff_id=models.CharField(max_length=25,primary_key=True)
	staff_name=models.CharField(max_length=40)
	password=models.CharField(max_length=12)
	email_id=models.EmailField()
	def __str__(self):
   		return self.staff_name

class dean(models.Model):
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	def __str__(self):
   		return self.faculty_id.name


class hod(models.Model):
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	def __str__(self):
   		return self.faculty_id.name


class advisor(models.Model):
	batch=models.ForeignKey(batch,on_delete=models.CASCADE)
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	class Meta:
		unique_together=('faculty_id','batch')
	def __str__(self):
   		return self.faculty_id.name
	
class teaches(models.Model):
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	course_id=models.ForeignKey(course,on_delete=models.CASCADE)
	semester=models.IntegerField(default=1, validators=[MaxValueValidator(2),MinValueValidator(1)])
	year=models.IntegerField()
	slot=models.CharField(max_length=2)
	min_cgpa_constraint=models.DecimalField(decimal_places=2,max_digits=3)
	batch = models.ManyToManyField(batch)
	prerequisite = models.ManyToManyField(course, related_name = "prerequisites", null=True, blank=True)
	class Meta:
		unique_together=('faculty_id','course_id','semester','year','slot')
	def __str__(self):
   		return self.course_id.title + " " + self.course_id.course_id

class takes(models.Model):
	student_obj=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	class Meta:
		unique_together=('student_obj','teaches')
	def __str__(self):
   		return self.student_obj.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title

class successfull_register(models.Model):
	student_id=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	class Meta:
		unique_together=('student_id','teaches')
	def __str__(self):
   		return self.student_id.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title

class token(models.Model):
	student_obj=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	status=models.IntegerField(default=1)
	reason=models.TextField(default = ":and:")

	class Meta:
		unique_together=('student_obj','teaches')
	def __str__(self):
   		return self.student_obj.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title

class grades(models.Model):
	student_id=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	grade=models.CharField(max_length=2)
	def __str__(self):
   		return self.student_id.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title


class current(models.Model):
	current_year = models.IntegerField(default=now.year)
	current_sem = models.IntegerField(default=1)
	def __str__(self):
		return str(self.current_year) + " " + str(self.current_sem)

class portalsOpen(models.Model):
	crp_open = models.BooleanField(default=False)
	grade_update_open = models.BooleanField(default=False)
	# crp_close=models.BooleanField(default=False)
	def __str__(self):
		return str(self.crp_open) +" " +str(self.grade_update_open)

studentportal/forms.py
from django import forms
from models import *
class StudentForm(forms.ModelForm):
    class Meta:
        model = student
        widgets = {
        'password': forms.PasswordInput(),
    }

class FacultyForm(forms.ModelForm):
    class Meta:
        model = faculty
        widgets = {
        'password': forms.PasswordInput(),
    }


class dean_staff_officeForm(forms.ModelForm):
    class Meta:
        model = dean_staff_office
        widgets = {
        'password': forms.PasswordInput(),
    }

studentportal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
import datetime
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.urls import reverse

# Create your views here.
global error_message
error_message = ''
now = datetime.datetime.now()
def index(request):
	template = loader.get_template('studentportal/login.html')
	context = {}
	if request.session.has_key('student_id'):
		return home(request)
	return HttpResponse(template.render(context, request))

def login_user(request):
	if request.session.has_key('student_id'):
		return home(request)
	if request.method == "POST":
	    student_id = request.POST['username']
	    password = request.POST['password']
	    if student_id is not None:
	    	if student.objects.filter(student_id = student_id).exists():
	    		student_obj = student.objects.get(student_id = student_id)
		    	if student_obj is None:
		        	context = {
		        		'error_message': 'Invalid login'
		        	}
		        	template = loader.get_template('studentportal/login.html')
		        	return HttpResponse(template.render(context, request))
		    	elif student_obj is not None:
		        	if student_obj.password == password:
		        		request.session['student_id'] = student_id
		        		return redirect('/studentportal/home')
		        	else:
		        		context = {'error_message': 'Invalid login'}
		        		template = loader.get_template('studentportal/login.html')
		        		return HttpResponse(template.render(context, request))
		    	else:
		        	context = {
		        		'error_message': 'Invalid login'
		        	}
		        	template = loader.get_template('studentportal/login.html')
		        	return HttpResponse(template.render(context, request))
	    	else:
		    	context = {'error_message': 'Invalid login'}
		    	template = loader.get_template('studentportal/login.html')
		    	return HttpResponse(template.render(context, request))
	return redirect('/studentportal/')


def logout_user(request):
	if request.session.has_key('student_id'):
		del request.session['student_id']
	return redirect('/studentportal/')
	
def home(request):
	if request.session.has_key('student_id'):
		student_id=request.session['student_id']
		template = loader.get_template('studentportal/home.html')
		student_obj = student.objects.get(student_id = student_id)
		takes_obj = takes.objects.filter(student_obj = student_obj)
		your_courses = []
		current_obj = current.objects.all()
		for obj in current_obj:
			current_year=obj.current_year
			current_sem=obj.current_sem
		for takes_t in takes_obj:
			if takes_t.teaches.year==current_year and takes_t.teaches.semester==current_sem:
				your_courses.append(takes_t.teaches)

					
				
		portal_objs = portalsOpen.objects.all()
		crp_open = False
		for portal_obj in portal_objs:
			crp_open = portal_obj.crp_open
		
		context = {'student_obj':student_obj,'your_courses':your_courses, 'crp_open':crp_open}
		return HttpResponse(template.render(context,request))
	else:
		return redirect('/studentportal/')
def view_grades(request):
	if request.session.has_key('student_id'):
		student_id=request.session['student_id']
		student_obj = student.objects.get(student_id = student_id)
		template = loader.get_template('studentportal/view_grades.html')
		grades_obj= grades.objects.filter(student_id = student_obj)
		print(grades_obj)
		context = {'student_obj':student_obj,'grades_obj':grades_obj}
		return HttpResponse(template.render(context,request))
	else:
		return redirect('/studentportal/')



		
def register_courses(request):
	if request.session.has_key('student_id'):

		portal_objs = portalsOpen.objects.all()
		crp_open = False
		for portal_obj in portal_objs:
			crp_open = portal_obj.crp_open
		if crp_open:
			student_id=request.session['student_id']
			template = loader.get_template('studentportal/register_courses.html')
			student_obj = student.objects.get(student_id = student_id)
			current_obj = current.objects.all()
			for obj in current_obj:
				current_year=obj.current_year
				current_sem=obj.current_sem


			to_your_batch = []
			to_other_batch = []
			teaches_objs_old = teaches.objects.filter(year = 1, semester = student_obj.current_sem)
			teaches_objs = []
			print(teaches_objs_old)
			# takes_obj = takes.objects.filter(student_obj = student_obj)
			# your_courses = []
			# for takes_t in takes_obj:
			# 	for batch in takes_t.teaches.batch.all():
			# 		if student_obj.current_year == batch.year:
			# 			your_courses.append(takes_t.teaches)
			
			for teaches_obj_old in teaches_objs_old:
				teaches_objs.append(teaches_obj_old)

			# for your_courses_tt in your_courses:
			# 	if your_courses_tt not in teaches_objs:
			# 		teaches_objs.append(your_courses_tt)
			# 	elif your_courses_tt in teaches_objs:
			# 		teaches_objs.remove(your_courses_tt)
			
			for teaches_t in teaches_objs:
				for batch_t in teaches_t.batch.all():
					if batch_t.dept == student_obj.dept_id and batch_t.year == student_obj.current_year:
						if teaches_t in to_other_batch:
							to_other_batch.remove(teaches_t)
						if teaches_t not in to_your_batch:
							to_your_batch.append(teaches_t)
					elif teaches_t not in to_your_batch and teaches_t not in to_other_batch:
							to_other_batch.append(teaches_t)
			successful_registered = []
			tokened = []
			success_reg_obj = successfull_register.objects.filter(student_id = student_obj)
			for success_reg_objs in success_reg_obj:
				if success_reg_objs.teaches in to_your_batch:
					to_your_batch.remove(success_reg_objs.teaches)
				if success_reg_objs.teaches in to_other_batch:
					to_other_batch.remove(success_reg_objs.teaches)
				successful_registered.append(success_reg_objs.teaches)


			tokened_obj = token.objects.filter(student_obj = student_obj)
			for tokened_objs in tokened_obj:
				if tokened_objs.teaches in to_your_batch:
					to_your_batch.remove(tokened_objs.teaches)
				elif tokened_objs.teaches in to_other_batch:
					to_other_batch.remove(tokened_objs.teaches)
				tokened.append(tokened_objs.teaches)
			global error_message
			context = {'student_obj':student_obj, 
				'to_your_batch': to_your_batch,
				'to_other_batch': to_other_batch, 
			 	'successful_registered': successful_registered,
			 	'tokened': tokened,
			 	'error_message': error_message
			}
			error_message = ''
			return HttpResponse(template.render(context,request))
		else:
			return redirect('/studentportal/')

	else:
		return redirect('/studentportal/')



def add_course_batch(request):
	global error_message

	if request.session.has_key('student_id'):
		selected_course = request.POST['Add_Course']
		student_id=request.session['student_id']
		course_attr = selected_course.split('+')
		faculty_id = (course_attr[0])
		course_id = (course_attr[1])
		semester = int(course_attr[2])
		year = int(course_attr[3])
		slot = str(course_attr[4])


		student_obj = student.objects.get(student_id = student_id)
		faculty_id_obj = faculty.objects.get(faculty_id = faculty_id)
		course_id_obj = course.objects.get(course_id = course_id)
		course_tokened = False
		selected_course_obj = teaches.objects.get(faculty_id = faculty_id_obj, course_id = course_id_obj, semester = semester, year = year, slot = slot)
		# cgpa constraint
		takes_obj = takes.objects.filter(student_obj = student_obj)
		years = []
		for takes_t in takes_obj:
			for batch in takes_t.teaches.batch.all():
				years.append(batch.year)

		same_slot_courses = []
		successfull_register_objs = successfull_register.objects.filter(student_id = student_obj)
		for teaches_t in successfull_register_objs:
			if teaches_t.teaches.slot == slot:
				same_slot_courses.append(teaches_t)
		#same slot
		if len(same_slot_courses) > 0:
			global error_message
			error_message = 'You have a course registered in same slot.'
			return redirect('studentportal:register_courses')


		if selected_course_obj.min_cgpa_constraint > student_obj.cgpa:
			token_tttt = token(student_obj = student_obj,teaches = selected_course_obj,status = 1, reason = "CGPA not satisfied")
			
			error_message = ''
			course_tokened = True
		
		course_credit = 0
		n = int(selected_course_obj.course_id.credit_struct)
		while n:
			course_credit, n = course_credit + n % 10, n // 10
		# credit limit
		if student_obj.curr_registered_credits + course_credit > student_obj.max_credit:
			if course_tokened == False:
				token_tttt = token(student_obj = student_obj,teaches = selected_course_obj,status = 1, reason = "Credit limit not satisfied")
			else:
				token_tttt.reason = token_tttt.reason + " :and: " + "Credit limit not satisfied"
			
			error_message = ''
			token_tttt.save()
			course_tokened = True
		
		# prerequistes
		prerequistes_list = selected_course_obj.prerequisite.all()
		for prerequisite_tt in prerequistes_list:
			if teaches.objects.filter(course_id = prerequisite_tt.course_id).exists():
				prereq_teaches = teaches.objects.filter(course_id = prerequisite_tt.course_id)
				prereq_cleared = False
				for prereq_teaches_tt in prereq_teaches:
					if grades.objects.filter(student_id = student_obj, teaches = prereq_teaches_tt).exists():
						grades_obj_prereq = grades.objects.get(student_id = student_obj, teaches = prereq_teaches_tt)
						grade_prereq = grades_obj_prereq.grade
						if grade_prereq != 0:
							prereq_cleared = True
						else:
							if course_tokened == False:
								token_tttt = token(student_obj = student_obj,teaches = selected_course_obj,status = 1, reason = "Prerequisite not cleared")
								course_tokened = True
							else:
								token_tttt.reason = token_tttt.reason + " :and: " + "Prerequisite not cleared"
								course_tokened = True
			else:
				if course_tokened == False:

studentportal/templates/studentportal/home.html
<h2>Hello {{ student_obj.name }}</h2>

<h3>Your courses this semester</h3>
<ul>
	{% for courses in your_courses %}
	

	<li>{{courses.course_id.course_id}}: {{courses.course_id.title}} (LTP: {{courses.course_id.credit_struct}}) (Slot: {{courses.slot}})</li>
	
	{% endfor %}
</ul>
<h3>Department: {{student_obj.dept_id.dept_name}}</h3>
<h3>Current Year: {{student_obj.current_year}}</h3>
<h3>Current Semester: {{ student_obj.current_sem }}</h3>
<h3>Your Grade:  {{student_obj.cgpa}}</h3>
<h3>Current Registered Credits: {{student_obj.curr_registered_credits}}</h3>
<h3>Max Credit(This semester): {{student_obj.max_credit}}</h3>
<h3>Total Credits Passes: {{student_obj.total_credits}}</h3>
<a href="{% url 'studentportal:view_grades'%}">View Grades</a>
{% if crp_open %}
<a href="{% url 'studentportal:register_courses'%}">Register Courses</a>
{% endif %}
<br>
<br>
<br>

<a href="{% url 'studentportal:logout' %}">Logout</a>

studentportal/templates/studentportal/login.html
<head>
    <title>Student Login</title>
</head>
{% block title %}Student Log In{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'studentportal:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

studentportal/templates/studentportal/register_courses.html
<h3>The following courses are floated this semester. Kindly choose accrding to your credit limit</h3>
{%if error_message %}
	<p style="color: red">{{error_message}}</p>
{%endif%}
<h3>Courses floated to your batch</h3>
<ul>

{% for to_your_batch_objs in to_your_batch%}

<form action="{% url 'studentportal:add_course_batch'%}" method="post">
	{% csrf_token %}
	<li>{{to_your_batch_objs.course_id.course_id}}: {{to_your_batch_objs.course_id.title}} (LTP: {{to_your_batch_objs.course_id.credit_struct}}) (Slot: {{to_your_batch_objs.slot}})
	<button type="submit" name="Add_Course" value="{{to_your_batch_objs.faculty_id.faculty_id}}+{{to_your_batch_objs.course_id.course_id}}+{{to_your_batch_objs.semester}}+{{to_your_batch_objs.year}}+{{to_your_batch_objs.slot}}">Add Course</button>
	
	</li>
	
</form>
{% endfor %}
</ul>
<h3>Courses floated to other batches</h3>

<ul>
{% for to_other_batch_objs in to_other_batch%}

<form action="{% url 'studentportal:add_course_other_batch'%}" method="post">
	{% csrf_token %}
	<li>{{to_other_batch_objs.course_id.course_id}}: {{to_other_batch_objs.course_id.title}} (LTP: {{to_other_batch_objs.course_id.credit_struct}}) (Slot: {{to_other_batch_objs.slot}})
	<button type="submit" name="Add_Course" value="{{to_other_batch_objs.faculty_id.faculty_id}}+{{to_other_batch_objs.course_id.course_id}}+{{to_other_batch_objs.semester}}+{{to_other_batch_objs.year}}+{{to_other_batch_objs.slot}}">Add Course</button>
	
	</li>
</form>
{% endfor %}
</ul>
<h3>Registered courses</h3>
<ul>
{% for succ_reg_objs in successful_registered%}

<form action="{% url 'studentportal:delete_reg_course'%}" method="post">
	{% csrf_token %}
	<li>{{succ_reg_objs.course_id.course_id}}: {{succ_reg_objs.course_id.title}} (LTP: {{succ_reg_objs.course_id.credit_struct}}) (Slot: {{succ_reg_objs.slot}})
	<button type="submit" name="Remove_Course" value="{{succ_reg_objs.faculty_id.faculty_id}}+{{succ_reg_objs.course_id.course_id}}+{{succ_reg_objs.semester}}+{{succ_reg_objs.year}}+{{succ_reg_objs.slot}}">Remove Course</button>
	
	</li>
</form>

{% endfor %}
</ul>

<h3>Tokened courses</h3>

<ul>
{% for tokened_objs in tokened%}

<form action="{% url 'studentportal:delete_tokened_course'%}" method="post">
	{% csrf_token %}
	<li>{{tokened_objs.course_id.course_id}}: {{tokened_objs.course_id.title}} (LTP: {{tokened_objs.course_id.credit_struct}}) (Slot: {{tokened_objs.slot}})
	<button type="submit" name="Remove_Course" value="{{tokened_objs.faculty_id.faculty_id}}+{{tokened_objs.course_id.course_id}}+{{tokened_objs.semester}}+{{tokened_objs.year}}+{{tokened_objs.slot}}">Remove Course</button>
	
	</li>
</form>

{% endfor %}
</ul>
<a href="{% url 'studentportal:home' %}">Back To Home</a>

studentportal/templates/studentportal/view_grades.html
hello {{ student_obj.name }}

<br>
<h3>Your grades this semester</h3>
<ul>
	{% for subject in grades_obj %}

	 <li> Course Name:{{subject.teaches.course_id.title}}   Faculty Name:{{subject.teaches.faculty_id.name}} grade:{{subject.grade}}</li>
	
	{% endfor %}
</ul>


<a href="{% url 'studentportal:home' %}">Back to Home</a>