DBMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.generic.base import TemplateView


urlpatterns = [
    url('^$', views.index, name='index'),
    url('^admin/', admin.site.urls),
    url('^studentportal/', include('studentportal.urls')),
    url('^facultyportal/', include('facultyportal.urls')),
    url('^dean_staff_office/',include('dean_staff_office.urls'))
]

dean_staff_office/urls.py
from . import views
from django.conf.urls import url

app_name = 'dean_staff_office'

urlpatterns=[
	url('^$', views.index, name='index'),
	url('^logout/$', views.logout_user, name='logout'),
	url('^home/$', views.home, name='home'),
	url('^login/$', views.login_user, name='login'),
	url('^course_catalogue/', views.course_catalogue, name='course_catalogue'),
	url('^add_course', views.add_course, name='add_course'),
	url('^course_post', views.course_post, name='course_post'),
	url('^edit_course/(?P<course_id>[A-Za-z]*[0-9]+)', views.edit_course, name='edit_course'),
	url('^course_edit_post/(?P<course_id_prev>[A-Za-z]*[0-9]+)', views.course_edit_post, name='course_edit_post'),
	url('^student_catalogue', views.student_catalogue, name='student_catalogue'),
	url('^add_student', views.add_student, name='add_student'),
	url('^student_post', views.student_post, name='student_post'),
	url('^edit_student/(?P<student_id>[A-Za-z]*[0-9]+)', views.edit_student, name='edit_student'),
	url('^student_edit_post/(?P<student_id_prev>[A-Za-z]*[0-9]+)', views.student_edit_post, name='student_edit_post'),
	url('^add_hod', views.add_hod, name='add_hod'),
	url('^hod_db', views.hod_db, name='hod_db'),
	url('^add_advisor', views.add_advisor, name='add_advisor'),
	url('^advisor_db', views.advisor_db, name='advisor_db'),
	url('^update_sem_year_form' , views.update_sem_year_form , name = 'update_sem_year_form'),
	url('^update_sem_year' , views.update_sem_year , name = 'update_sem_year'),
	url('^faculty_catalogue/', views.faculty_catalogue, name='faculty_catalogue'),
	url('^add_faculty', views.add_faculty, name='add_faculty'),
	url('^faculty_post', views.faculty_post, name='faculty_post'),
	url('^edit_faculty/(?P<faculty_id>[A-Za-z]*[0-9]+)', views.edit_faculty, name='edit_faculty'),
	url('^faculty_edit_post/(?P<faculty_id_prev>[A-Za-z]*[0-9]+)', views.faculty_edit_post, name='faculty_edit_post'),
	url('^portal_open_close/', views.portal_open_close, name='portal_open_close'),
	url('^portals_post/', views.portals_post, name='portals_post'),
	url('^add_dean/', views.add_dean, name='add_dean'),
	url('^dean_db/', views.dean_db, name='dean_db')
]

facultyportal/urls.py
from . import views
from django.conf.urls import url


app_name = 'facultyportal'

urlpatterns = [
	url('^$', views.index, name='index'),
	url('^logout/', views.logout_user, name='logout'),
	url('^home/', views.home, name='home'),
	url('^login', views.login_user, name='login'),
	url('^grade/(?P<course_id>[A-Za-z0-9]+)', views.grade, name='grade'),
	url('^update_grade/(?P<student_id>[A-Za-z0-9]+)/(?P<course_id>[A-Za-z0-9]+)', views.update_grade, name='update_grade'),
	url('^add_course_float', views.add_course_float, name='add_course_float'),

	url('^float_new_courses', views.float_new_courses, name='float_new_courses'),
	url('^view_tokens', views.view_tokens, name='view_tokens'),
	url('^accept_close', views.accept_close, name='accept_close'),
	url('^reject_close', views.reject_close, name='reject_close'),
	url('^accept_pass', views.accept_pass, name='accept_pass'),

	url('^update_cgpa', views.update_cgpa, name='update_cgpa'),

	]

facultyportal/models.py
from django.db import models
from studentportal.models import *

# Create your models here.

facultyportal/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.template import loader
from django.http import HttpResponse
from .models import *
import datetime
import datetime
now = datetime.datetime.now()
# Create your views here.
now = datetime.datetime.now()
def index(request):
	template = loader.get_template('facultyportal/login.html')
	context = {}
	if request.session.has_key('faculty_id'):
		return home(request)
	return HttpResponse(template.render(context, request))

def login_user(request):
	if request.session.has_key('faculty_id'):
		return home(request)
	if request.method == "POST":
	    faculty_id = request.POST['username']
	    password = request.POST['password']
	    if faculty_id is not None:
	    	faculty_obj = faculty.objects.get(faculty_id = faculty_id)
	    	if faculty_obj is None:
	        	context = {
	        		'error_message': 'Invalid login'
	        	}
	        	template = loader.get_template('facultyportal/login.html')
	        	return HttpResponse(template.render(context, request))
	    	elif faculty_obj is not None:
	        	if faculty_obj.password == password:
	        		request.session['faculty_id'] = faculty_id
	        		return redirect('/facultyportal/home')
	        	else:
	        		context = {'error_message': 'Invalid login'}
	        		template = loader.get_template('facultyportal/login.html')
	        		return HttpResponse(template.render(context, request))
	    	else:
	        	context = {
	        		'error_message': 'Invalid login'
	        	}
	        	template = loader.get_template('facultyportal/login.html')
	        	return HttpResponse(template.render(context, request))
	template = loader.get_template('facultyportal/login.html')
	return redirect('/facultyportal/')


def logout_user(request):
	if request.session.has_key('faculty_id'):
		del request.session['faculty_id']
	if request.session.has_key('dean_id'):
		del request.session['dean_id']
	return redirect('/facultyportal/')

def update_cgpa(request):
    if request.session.has_key('faculty_id'):
        student_all = student.objects.all()

        for student_obj in student_all:
        	prev_cgpa = student_obj.cgpa
        	prev_credit = student_obj.total_credits
        	current_obj = current.objects.all()
        	for obj in current_obj:
        		curr_year=obj.current_year
        		curr_sem=obj.current_sem
        	if(curr_sem == 1):
        		prev_sem = 2
        		prev_year = curr_year -1
        	elif(curr_sem == 2):
        		prev_sem = 1
        		prev_year = curr_year
        	course_stu_list = grades.objects.filter(student_id = student_obj)
        	sums = 0
        	add_credit = 0
        	prev_sem_credit=0
        	for c in course_stu_list:
        		if(int(c.grade)>=4 and c.teaches.semester == prev_sem and c.teaches.year == prev_year ):
        			course_obj = course.objects.get(course_id = c.teaches.course_id.course_id)
        			credit = course_obj.credit_struct
        			t_credit = 0
        			for d in credit:
        				t_credit=t_credit+int(d)
        			prev_sem_credit = prev_sem_credit+t_credit
        		elif(int(c.grade)>=4 and c.teaches.semester == curr_sem and c.teaches.year == curr_year ):
        			course_obj = course.objects.get(course_id = c.teaches.course_id.course_id)
        			credit = course_obj.credit_struct
        			t_credit = 0
        			for d in credit:
        				t_credit=t_credit+int(d)
        			add_credit = add_credit + t_credit
        			sums = sums + t_credit*int(c.grade)
        	sums = (sums + prev_cgpa*student_obj.total_credits)/(student_obj.total_credits+add_credit)
        	student_obj.total_credits = student_obj.total_credits+add_credit
        	student_obj.cgpa =  sums
        	div=2
        	if student_obj.current_year==1 and student_obj.current_sem==1:
        		div=1
        	student_obj.max_credit = 1.25*(add_credit+prev_sem_credit)/div
        	student_obj.save()
    return redirect('/facultyportal/home')





def home(request):
	if request.session.has_key('faculty_id'):
		faculty_id=request.session['faculty_id']
		template = loader.get_template('facultyportal/home.html')
		faculty_obj = faculty.objects.get(faculty_id = faculty_id)
		teaches_obj = teaches.objects.filter(faculty_id = faculty_id)
		current_obj = current.objects.all()
		for obj in current_obj:
			current_year=obj.current_year
			current_sem=obj.current_sem
		dean_list = dean.objects.all()
		is_dean = False
		for h in dean_list:
			if(h.faculty_id == faculty_obj):
				d = faculty_obj.dept_id
				is_dean = True				
				
		if is_dean:
			request.session['dean_id'] = faculty_id

	#		for batch in takes_t.teaches.batch.all():
	#			years.append(batch.year)
	#	context = {'faculty_obj':faculty_obj,'takes_obj':takes_obj, 'years': years}
		context = {'is_dean':is_dean,'faculty_obj':faculty_obj,'teaches_obj':teaches_obj,'current_year':current_year,'current_sem':current_sem}
		return HttpResponse(template.render(context,request))
	else:
		return redirect('/facultyportal/')

def grade(request, course_id):
	if request.session.has_key('faculty_id'):
		faculty_id=request.session['faculty_id']
		template = loader.get_template('facultyportal/grade.html')
		# faculty_id=faculty.objects.filter(faculty_id=faculty_id)
		faculty_obj = faculty.objects.get(faculty_id=faculty_id)
		current_obj = current.objects.all()
		for obj in current_obj:
			current_year=obj.current_year
			current_sem=obj.current_sem

		teaches_obj=teaches.objects.get(faculty_id=faculty_id,year=current_year,semester=current_sem,course_id=course_id)
		takes_obj = takes.objects.filter(teaches=teaches_obj)
		
		grades_list = ['--', '10', '9', '8', '7', '6', '5', '4', '0']

		student_grade_exist_list = []
		student_grade_not_exist_list =[]
		for students in takes_obj:
			if grades.objects.filter(student_id = students.student_obj, teaches = teaches_obj).exists():
				student_grade_exist_list.append(grades.objects.get(student_id = students.student_obj, teaches = teaches_obj))
			else:
				student_grade_not_exist_list.append(students)
		portal_objs = portalsOpen.objects.all()
		grade_update_open = False
		for portal_obj in portal_objs:
			grade_update_open = portal_obj.grade_update_open
	#		for batch in takes_t.teaches.batch.all():
	#			years.append(batch.year)
	#	context = {'faculty_obj':faculty_obj,'takes_obj':takes_obj, 'years': years}


		# <!-- {% if student_n.student_obj in student_grade_exist_list%} -->
  #               <!-- <option value="{{student_grades_list.objects.get(student_id = student_n.student_obj).grade}}">{{student_grades_list.objects.get(student_id = student_n.student_obj).grade}}</option>
  #           {% else %} -->
		context = {
			'faculty_obj':faculty_obj,
			'grades_list': grades_list, 
			'grade_update_open': grade_update_open, 
			'student_grade_exist_list':student_grade_exist_list,
			'student_grade_not_exist_list':student_grade_not_exist_list,
		}

		return HttpResponse(template.render(context,request))
	else:
		return redirect('/facultyportal/')
		
def update_grade(request,student_id,course_id):
	if request.session.has_key('faculty_id'):
		faculty_id=request.session['faculty_id']

		grade=request.POST['grade']
		print(student_id)
		print(course_id)
		print(grade)
		
		student_obj=student.objects.get(student_id=student_id)
		current_obj = current.objects.all()
		for obj in current_obj:
			current_year=obj.current_year
			current_sem=obj.current_sem
		teaches_obj=teaches.objects.get(faculty_id=faculty_id,year=current_year,semester=current_sem,course_id=course_id)
		if grades.objects.filter(student_id=student_obj,teaches=teaches_obj).exists():
			grade_obj = grades.objects.get(student_id=student_obj,teaches=teaches_obj)
			grade_obj.grade=grade

		else:
			grade_obj = grades(student_id=student_obj,teaches=teaches_obj,grade=grade)
		grade_obj.save()
			

		return redirect('/facultyportal/grade/'+course_id)
	else:
		return redirect('/facultyportal/')





def float_new_courses(request):
	if request.session.has_key('faculty_id'):
		faculty_id=request.session['faculty_id']
		template = loader.get_template('facultyportal/float_new_courses.html')

		current_obj = current.objects.all()
		for obj in current_obj:
			current_year = obj.current_year
			current_sem = obj.current_sem


		batch_list = []
		batch_obj = batch.objects.all()
		
		faculty_obj = faculty.objects.get(faculty_id = faculty_id)
		faculty_dept_id = faculty_obj.dept_id
		
		c_dept = course.objects.filter(dept_id = faculty_dept_id)
		courses_of_dept=[]
		courses_not_floated = []
		for c in c_dept:
			if(not teaches.objects.filter(course_id = c.course_id , faculty_id = faculty_id, semester = current_sem, year = current_year).exists()):
				courses_not_floated.append(c)
			courses_of_dept.append(c)
	
		context = {'courses_of_dept':courses_of_dept, 
					'courses_not_floated':courses_not_floated,
				   'batch_obj':batch_obj
			
		}
		return HttpResponse(template.render(context,request))
	else:
		return redirect('/facultyportal/')


def add_course_float(request):
	if request.session.has_key('faculty_id'):
		faculty_id = request.session['faculty_id']
		faculty_obj = faculty.objects.get(faculty_id = faculty_id)
		course_id = request.POST['course_floated']
		print(course_id)
		course_obj = course.objects.get(course_id = course_id)
		current_obj = current.objects.all()
		for obj in current_obj:
			current_year = obj.current_year
			current_sem = obj.current_sem 
		slot = request.POST['slot']
		min_cg = request.POST['min_cg']

		batch_tt = request.POST.getlist('batches')
		batch_obj_list = []
		for b in batch_tt:
			ba = b.split('+')
			print(ba)
			year = ba[1]
			dept = ba[0]
			print(dept)
			dept_obj = department.objects.get(dept_id = dept)
			bat = batch.objects.get(year = year , dept = dept_obj)
			batch_obj_list.append(bat)

		prereq_tt = request.POST.getlist('prerequisite')
		prereq_obj_list = []
		for b in prereq_tt:
			if b != course_id:

facultyportal/templates/facultyportal/float_new_courses.html

<body>
<h3>Select the courses you need to float and specify the required details</h3>


<form action="{% url 'facultyportal:add_course_float'%}" method="post">
  {% csrf_token %}

  Select a Course to be floated
  <div id="selector">
  <select name = "course_floated" id = "course_floated" required>
      <option value="">--</option>
  	   {% for courses in courses_not_floated %}
  		 <option value={{courses.course_id}}>{{courses.title}}</option>
       {% endfor %}
 
  </select> <br><br>
</div>
Write the slot
 <input name="slot" type="text" required> 
 <br><br>

Minimum CGPA criteria (1-10)
 <input type="number" name="min_cg" min="0" max="10" required>
 <br><br>
 
Select the batch
 <select name = "batches" multiple required>
   {% for batch in batch_obj %}
   <option value="{{batch.dept.dept_id}}+{{batch.year}}">{{batch.year}} {{batch.dept}}</option>
   {% endfor %}
 </select>
 <br>
 <br>

Select the prerequisite courses 
<div id="selector2">
  <select name = "prerequisite" id="prerequisite" multiple>
       {% for courses in courses_of_dept %}

       <option value={{courses.course_id}}>{{courses.title}}</option>
       {% endfor %}
 
  </select>
  </div>
<br><br>
<p id="demo"></p>
<input type="submit" name="Submit" value="submit">
</form>
<a href="{% url 'facultyportal:home'%}">Back to Home</a>

</body>

facultyportal/templates/facultyportal/grade.html
<h2>Hello {{ faculty_obj.name }}</h2>
<br>
<h3>Your students this semester</h3>
<ul>
    {% for student_n in student_grade_exist_list %}    
    <li>{{student_n.student_id.name}} </li>  
    {% if grade_update_open %}
      Enter the grade
      <form action="/facultyportal/update_grade/{{student_n.student_id.student_id}}/{{student_n.teaches.course_id.course_id}}" method='post'>
      	{% csrf_token %}
        <select name="grade">
            {% for grade in grades_list %}
            {% if student_n.grade == grade %}
            <option value="{{student_n.grade}}" selected="selected">{{student_n.grade}}</option>
            {% else %}
            <option value="{{grade}}">{{grade}}</option>
            {% endif %}
           {% endfor %}
        </select>

    <input type="submit" value="update">
    </form>
  {% endif %}
  {% endfor %}
{% for student_n in student_grade_not_exist_list %}    
    <li>{{student_n.student_obj.name}} </li>  
    {% if grade_update_open %}
      Enter the grade
      <form action="/facultyportal/update_grade/{{student_n.student_obj.student_id}}/{{student_n.teaches.course_id.course_id}}" method='post'>
        {% csrf_token %}
        <select name="grade">
            {% for grade in grades_list %}
                <option value="{{grade}}">{{grade}}</option>
            {% endfor %}
        </select>

    <input type="submit" value="update">
    </form>
  {% endif %}
  {% endfor %}
   
</ul>

<a href="{% url 'facultyportal:home'%}">Back to Home</a>

  
  

facultyportal/templates/facultyportal/home.html
hello {{ faculty_obj.name }}

<br>
<h3>Your courses this semester</h3>
<ul>
    {% for teaches in teaches_obj %}

    {% if current_year == teaches.year and current_sem == teaches.semester  %}
    <li><a href="{% url 'facultyportal:grade' course_id=teaches.course_id.course_id %}">{{teaches.course_id}}: {{teaches.course_id.title}} (LTP: {{teaches.course_id.credit_struct}}) (Slot: {{teaches.slot}})</a></li>
    {% endif %}
    {% endfor %}
</ul>
<h3>Department: {{faculty_obj.dept_id.dept_name}}</h3>

<h3>Email_id: {{faculty_obj.email_id}}</h3>

<a href="{% url 'facultyportal:view_tokens' %}">View Tokens</a>
<br>
<br>
<a href="{% url 'facultyportal:float_new_courses'%}">Float Courses</a> 
<br>
{% if is_dean%}
<a href="{% url 'dean_staff_office:login'%}" target="blank">Dean Login</a>
{% endif%}
<br>
<a href="{% url 'facultyportal:logout' %}">Logout</a>

<br>

facultyportal/templates/facultyportal/login.html
<head>
    <title>Faculty Login</title>
</head>
{% block title %}Faculty Log In{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'facultyportal:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

facultyportal/templates/facultyportal/token.html
<br>
<h3>Your tokens this semester</h3>
<ul>
    {% for tokens in teaches_course_tokens %}
    
    <li>
    	<div>
    		<p>Student Name: {{tokens.student_obj.name}}<br>
    		Course ID: {{tokens.teaches.course_id.course_id}}<br>
    		Course Name: {{tokens.teaches.course_id.title}}<br>
    		Course LTP Structure: {{tokens.teaches.course_id.credit_struct}}<br>
    		Course Slot: {{tokens.teaches.slot}}<br>
    		Token Reason: {{tokens.reason}}</p>
            <form method="post" action="{% url 'facultyportal:accept_close' %}">
        {% csrf_token %}
    		<button type="submit" name="accept_close" value="{{tokens.student_obj.student_id}}+{{tokens.teaches.course_id.course_id}}+{{tokens.teaches.semester}}+{{tokens.teaches.year}}+{{tokens.teaches.faculty_id.faculty_id}}">Accept &amp; Close</button>
        </form>
        <form method="post" action="{% url 'facultyportal:reject_close' %}">
        {% csrf_token %}
            <button type="submit" name="reject_close" value="{{tokens.student_obj.student_id}}+{{tokens.teaches.course_id.course_id}}+{{tokens.teaches.semester}}+{{tokens.teaches.year}}+{{tokens.teaches.faculty_id.faculty_id}}">Reject</button>
        </form>
        {%if is_dean == False%}
        <form method="post" action="{% url 'facultyportal:accept_pass' %}">
        {% csrf_token %}
            <button type="submit" name="accept_pass" value="{{tokens.student_obj.student_id}}+{{tokens.teaches.course_id.course_id}}+{{tokens.teaches.semester}}+{{tokens.teaches.year}}+{{tokens.teaches.faculty_id.faculty_id}}">Accept &amp; Pass</button>
        </form>
        {%endif%}
    	</div>
    </li>
    </form>
    {% endfor %}
</ul>

<a href="{% url 'facultyportal:home'%}">Back to Home</a> 