DBMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.views.generic.base import TemplateView


urlpatterns = [
    url('^$', views.index, name='index'),
    url('^admin/', admin.site.urls),
    url('^studentportal/', include('studentportal.urls')),
    url('^facultyportal/', include('facultyportal.urls')),
    url('^dean_staff_office/',include('dean_staff_office.urls'))
]

dean_staff_office/urls.py
from . import views
from django.conf.urls import url

app_name = 'dean_staff_office'

urlpatterns=[
	url('^$', views.index, name='index'),
	url('^logout/$', views.logout_user, name='logout'),
	url('^home/$', views.home, name='home'),
	url('^login/$', views.login_user, name='login'),
	url('^course_catalogue/', views.course_catalogue, name='course_catalogue'),
	url('^add_course', views.add_course, name='add_course'),
	url('^course_post', views.course_post, name='course_post'),
	url('^edit_course/(?P<course_id>[A-Za-z]*[0-9]+)', views.edit_course, name='edit_course'),
	url('^course_edit_post/(?P<course_id_prev>[A-Za-z]*[0-9]+)', views.course_edit_post, name='course_edit_post'),
	url('^student_catalogue', views.student_catalogue, name='student_catalogue'),
	url('^add_student', views.add_student, name='add_student'),
	url('^student_post', views.student_post, name='student_post'),
	url('^edit_student/(?P<student_id>[A-Za-z]*[0-9]+)', views.edit_student, name='edit_student'),
	url('^student_edit_post/(?P<student_id_prev>[A-Za-z]*[0-9]+)', views.student_edit_post, name='student_edit_post'),
	url('^add_hod', views.add_hod, name='add_hod'),
	url('^hod_db', views.hod_db, name='hod_db'),
	url('^add_advisor', views.add_advisor, name='add_advisor'),
	url('^advisor_db', views.advisor_db, name='advisor_db'),
	url('^update_sem_year_form' , views.update_sem_year_form , name = 'update_sem_year_form'),
	url('^update_sem_year' , views.update_sem_year , name = 'update_sem_year'),
	url('^faculty_catalogue/', views.faculty_catalogue, name='faculty_catalogue'),
	url('^add_faculty', views.add_faculty, name='add_faculty'),
	url('^faculty_post', views.faculty_post, name='faculty_post'),
	url('^edit_faculty/(?P<faculty_id>[A-Za-z]*[0-9]+)', views.edit_faculty, name='edit_faculty'),
	url('^faculty_edit_post/(?P<faculty_id_prev>[A-Za-z]*[0-9]+)', views.faculty_edit_post, name='faculty_edit_post'),
	url('^portal_open_close/', views.portal_open_close, name='portal_open_close'),
	url('^portals_post/', views.portals_post, name='portals_post'),
	url('^add_dean/', views.add_dean, name='add_dean'),
	url('^dean_db/', views.dean_db, name='dean_db')
]

dean_staff_office/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

studentportal/models.py
from __future__ import unicode_literals
from django import forms
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime
# Create your models here.
now = datetime.datetime.now()
class department(models.Model):
	dept_id=models.IntegerField()
	dept_name=models.CharField(max_length=25)
	def __str__(self):
   		return self.dept_name

class batch(models.Model):
	dept=models.ForeignKey(department,on_delete=models.CASCADE)
	year=models.IntegerField(validators=[MaxValueValidator(4),MinValueValidator(1)])
	def __str__(self):
		return self.dept.dept_name + " " + str(self.year)


class student(models.Model):
	student_id=models.CharField(max_length=25,primary_key=True)
	name=models.CharField(max_length=40)
	dept_id=models.ForeignKey(department,on_delete=models.CASCADE)
	cgpa=models.DecimalField(decimal_places=2,max_digits=10,default=0)
	curr_registered_credits=models.IntegerField(default=0)
	max_credit=models.DecimalField(default=24, max_digits=10, decimal_places=2)
	total_credits=models.DecimalField(default=0, max_digits=10, decimal_places=2)
	current_year=models.IntegerField(validators=[MaxValueValidator(4),MinValueValidator(1)],default=1)
	current_sem=models.IntegerField(validators=[MaxValueValidator(2),MinValueValidator(1)],default=1)
	password=models.CharField(max_length=50,default="abcdefgh")
	student_email=models.CharField(max_length=100, default="")	
	def __str__(self):
   		return self.name


class course(models.Model):
	course_id=models.CharField(max_length=25,primary_key=True)
	credit_struct=models.CharField(max_length=25)
	title=models.CharField(max_length=40)
	dept_id=models.ForeignKey(department,on_delete=models.CASCADE)
	def __str__(self):
   		return self.title


class faculty(models.Model):
	faculty_id=models.CharField(max_length=25,primary_key=True)
	name=models.CharField(max_length=40)
	dept_id=models.ForeignKey(department,on_delete=models.CASCADE)
	password=models.CharField(max_length=12, default="abcdefgh")
	email_id=models.EmailField()
	def __str__(self):
   		return self.name

class dean_staff_office(models.Model):
	staff_id=models.CharField(max_length=25,primary_key=True)
	staff_name=models.CharField(max_length=40)
	password=models.CharField(max_length=12)
	email_id=models.EmailField()
	def __str__(self):
   		return self.staff_name

class dean(models.Model):
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	def __str__(self):
   		return self.faculty_id.name


class hod(models.Model):
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	def __str__(self):
   		return self.faculty_id.name


class advisor(models.Model):
	batch=models.ForeignKey(batch,on_delete=models.CASCADE)
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	class Meta:
		unique_together=('faculty_id','batch')
	def __str__(self):
   		return self.faculty_id.name
	
class teaches(models.Model):
	faculty_id=models.ForeignKey(faculty,on_delete=models.CASCADE)
	course_id=models.ForeignKey(course,on_delete=models.CASCADE)
	semester=models.IntegerField(default=1, validators=[MaxValueValidator(2),MinValueValidator(1)])
	year=models.IntegerField()
	slot=models.CharField(max_length=2)
	min_cgpa_constraint=models.DecimalField(decimal_places=2,max_digits=3)
	batch = models.ManyToManyField(batch)
	prerequisite = models.ManyToManyField(course, related_name = "prerequisites", null=True, blank=True)
	class Meta:
		unique_together=('faculty_id','course_id','semester','year','slot')
	def __str__(self):
   		return self.course_id.title + " " + self.course_id.course_id

class takes(models.Model):
	student_obj=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	class Meta:
		unique_together=('student_obj','teaches')
	def __str__(self):
   		return self.student_obj.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title

class successfull_register(models.Model):
	student_id=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	class Meta:
		unique_together=('student_id','teaches')
	def __str__(self):
   		return self.student_id.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title

class token(models.Model):
	student_obj=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	status=models.IntegerField(default=1)
	reason=models.TextField(default = ":and:")

	class Meta:
		unique_together=('student_obj','teaches')
	def __str__(self):
   		return self.student_obj.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title

class grades(models.Model):
	student_id=models.ForeignKey(student,on_delete=models.CASCADE)
	teaches=models.ForeignKey(teaches,on_delete=models.CASCADE)
	grade=models.CharField(max_length=2)
	def __str__(self):
   		return self.student_id.name + " " + self.teaches.faculty_id.name + " " + self.teaches.course_id.title


class current(models.Model):
	current_year = models.IntegerField(default=now.year)
	current_sem = models.IntegerField(default=1)
	def __str__(self):
		return str(self.current_year) + " " + str(self.current_sem)

class portalsOpen(models.Model):
	crp_open = models.BooleanField(default=False)
	grade_update_open = models.BooleanField(default=False)
	# crp_close=models.BooleanField(default=False)
	def __str__(self):
		return str(self.crp_open) +" " +str(self.grade_update_open)

dean_staff_office/templates/dean_staff_office/add.html
<h2>Hello Want to add Hod</h2>
<br>


{% if error_message %}
 <p style="color: red"><strong>{{ error_message }}</strong></p>
{% endif %}
 {% if good_message %}
 <p style="color: blue"><strong>{{good_message}}</strong></p>
{% endif %}



<form action="{% url 'dean_staff_office:hod_db'%}" method='post'>
{% csrf_token %}
<div class="col-sm-10">

    Select the department
    <select name="dept" required>
        <option value="">--</option>
        {% for dept in departments%}
        {% if dept %}
        <option value="{{dept.dept_id}}" >{{dept.dept_name}}</option>
        {% endif %}
        {% endfor %}
    </select>
</div>
  
  
<br>
<br>
<div class="col-sm-10">

Select the faculty
    <select name="faculty" required>
        <option value="">--</option>
        {% for faculty in faculty_obj%}
        {% if faculty %}
        <option value="{{faculty.faculty_id}}">{{faculty.name}}</option>
        {% endif %}
        {% endfor %}
    </select>
</div>
  
  <br>
<input type="submit" value="Add">

  </form>


<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/add_advisor.html
<h2>Hello Want to add Advisor</h2>
<br>


{% if error_message %}
 <p style="color: red"><strong>{{ error_message }}</strong></p>
{% endif %}
 {% if good_message %}
 <p style="color: blue"><strong>{{good_message}}</strong></p>
{% endif %}





<form action="{% url 'dean_staff_office:advisor_db'%}" method='post'>
{% csrf_token %}
<div class="col-sm-10">
    Select the batch
    <select name="batch" required>
        <option value="">--</option>
        {% for batch in batch_obj%}
        {% if batch %}

        <option value="{{batch.year}}+{{batch.dept.dept_id}}">{{batch.year}} {{batch.dept.dept_name}}</option>
        {% endif %}
        {% endfor %}
    </select>
</div>
  
  
<br>
<br>
<div class="col-sm-10">
    Select the faculty
    <select name="faculty" required>
        <option value="">--</option>
        {% for faculty in faculty_obj%}
        {% if faculty %}
        <option value="{{faculty.faculty_id}}" >{{faculty.name}}</option>
        {% endif %}
        {% endfor %}
    </select>
</div>
<br>
<input type="submit" value="Add">

  </form>


<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/add_course.html
<head>
    <title>Add New Course</title>
</head>
{% block title %}Add New Course{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    {% if error_message %}
                        <p style="color: red"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% if good_message %}
                        <p style="color: blue"><strong>{{good_message}}</strong></p>
                    {% endif %}
                    {% if course_obj %}
                    <form class="form-horizontal" role="form" action="/dean_staff_office/course_edit_post/{{course_obj.course_id}}" method="post" enctype="multipart/form-data">
                    {% else %}
                    <form class="form-horizontal" role="form" action="{% url 'dean_staff_office:course_post'%}" method="post" enctype="multipart/form-data">
                    {% endif %}
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_course_id">
                                Course ID:
                            </label>
                            <div class="col-sm-10">
                                {% if course_obj%}
                                <input id="id_course_id" maxlength="30" name="course_id" type="text" value="{{course_obj.course_id}}" required>
                                {% else %}
                                <input id="id_course_id" maxlength="30" name="course_id" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_course_title">
                                Course Title:
                            </label>
                            <div class="col-sm-10">
                                {% if course_obj %}
                                <input id="id_course_title" maxlength="30" name="course_title" type="text" value="{{course_obj.title}}" required>
                                {% else %}
                                <input id="id_course_title" maxlength="30" name="course_title" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_course_ltp_struct">
                                LTP Structure:
                            </label>
                            <div class="col-sm-10">
                                {% if course_obj %}
                                <input id="id_course_ltp_struct" maxlength="30" name="course_ltp_struct" type="text" value="{{course_obj.credit_struct}}" required>
                                {% else %}
                                <input id="id_course_ltp_struct" maxlength="30" name="course_ltp_struct" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2">
                                Department:
                            </label>
                            <div class="col-sm-10">
                                <select name="course_dept" required>
                                    <option value="">--</option>
                                    {% for dept in dept_objs%}
                                    {% if course_obj %}
                                        {% if dept.dept_id == course_obj.dept_id.dept_id%}
                                        <option value="{{dept.dept_id}}" selected="selected">{{dept.dept_name}}</option>
                                        {% else %}
                                        <option value="{{dept.dept_id}}">{{dept.dept_name}}</option>
                                        {% endif %}
                                    {% else %}
                                        <option value="{{dept.dept_id}}">{{dept.dept_name}}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                {% if course_obj %}
                                <button type="submit" class="btn btn-success">Save Course</button>
                                {% else %}
                                <button type="submit" class="btn btn-success">Add Course</button>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<a href="{% url 'dean_staff_office:course_catalogue'%}">Back to Course Catalogue</a>
<br>
<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>
</div>

{% endblock %}

dean_staff_office/templates/dean_staff_office/add_dean.html
<h2>Hello Want to Add/Edit Dean</h2>
<br>


{% if error_message %}
 <p style="color: red"><strong>{{ error_message }}</strong></p>
{% endif %}
 {% if good_message %}
 <p style="color: blue"><strong>{{good_message}}</strong></p>
{% endif %}



<form action="{% url 'dean_staff_office:dean_db'%}" method='post'>
{% csrf_token %}
<div class="col-sm-10">

Select the faculty
    <select name="faculty" required>
        <option value="">--</option>
        {% for faculty in faculty_obj%}
        {% if faculty %}
        <option value="{{faculty.faculty_id}}">{{faculty.name}}</option>
        {% endif %}
        {% endfor %}
    </select>
</div>
  
  <br>
<input type="submit" value="Add Dean">

  </form>


<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/add_faculty.html
<head>
    <title>Add New Faculty</title>
</head>
{% block title %}Add New Faculty{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    {% if error_message %}
                        <p style="color: red"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% if good_message %}
                        <p style="color: blue"><strong>{{good_message}}</strong></p>
                    {% endif %}
                    {% if faculty_obj %}
                    <form class="form-horizontal" role="form" action="/dean_staff_office/faculty_edit_post/{{faculty_obj.faculty_id}}" method="post" enctype="multipart/form-data">
                    {% else %}
                    <form class="form-horizontal" role="form" action="{% url 'dean_staff_office:faculty_post'%}" method="post" enctype="multipart/form-data">
                    {% endif %}
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_faculty_id">
                                Faculty ID:
                            </label>
                            <div class="col-sm-10">
                                {% if faculty_obj%}
                                <input id="id_faculty_id" maxlength="30" name="faculty_id" type="text" value="{{faculty_obj.faculty_id}}" required>
                                {% else %}
                                <input id="id_faculty_id" maxlength="30" name="faculty_id" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_faculty_title">
                                Faculty Name:
                            </label>
                            <div class="col-sm-10">
                                {% if faculty_obj %}
                                <input id="id_faculty_title" maxlength="30" name="faculty_title" type="text" value="{{faculty_obj.name}}" required>
                                {% else %}
                                <input id="id_faculty_title" maxlength="30" name="faculty_title" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2">
                                Department:
                            </label>
                            <div class="col-sm-10">
                                <select name="faculty_dept" required>
                                    <option value="">--</option>
                                    {% for dept in dept_objs%}
                                    {% if faculty_obj %}
                                        {% if dept.dept_id == faculty_obj.dept_id.dept_id%}
                                        <option value="{{dept.dept_id}}" selected="selected">{{dept.dept_name}}</option>
                                        {% else %}
                                        <option value="{{dept.dept_id}}">{{dept.dept_name}}</option>
                                        {% endif %}
                                    {% else %}
                                        <option value="{{dept.dept_id}}">{{dept.dept_name}}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                {% if faculty_obj %}
                                <button type="submit" class="btn btn-success">Save faculty</button>
                                {% else %}
                                <button type="submit" class="btn btn-success">Add faculty</button>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<a href="{% url 'dean_staff_office:faculty_catalogue'%}">Back to faculty Catalogue</a>
<br>
<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>
</div>

{% endblock %}

dean_staff_office/templates/dean_staff_office/add_student.html
<head>
    {% if student_obj%}
    <title>Edit Student</title>
    {% else %}
    <title>Add New Student</title>
    {%endif%}
</head>
{% block title %}
{% if student_obj %}
Edit Student
{% else %}
Add New Student
{% endif %}
{% endblock %}
{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    
                    {% if error_message %}
                        <p style="color: red"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% if good_message %}
                        <p style="color: blue"><strong>{{good_message}}</strong></p>
                    {% endif %}
                    {% if student_obj %}
                    <form class="form-horizontal" role="form" action="/dean_staff_office/student_edit_post/{{student_obj.student_id}}" method="post" enctype="multipart/form-data">
                    {% else %}
                    <form class="form-horizontal" role="form" action="{% url 'dean_staff_office:student_post'%}" method="post" enctype="multipart/form-data">
                    {% endif %}
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_student_id">
                                Student ID:
                            </label>
                            <div class="col-sm-10">
                                {% if student_obj%}
                                <input id="id_student_id" maxlength="30" name="student_id" type="text" value="{{student_obj.student_id}}" required>
                                {% else %}
                                <input id="id_student_id" maxlength="30" name="student_id" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_student_title">
                                Student Name:
                            </label>
                            <div class="col-sm-10">
                                {% if student_obj %}
                                <input id="id_student_title" maxlength="30" name="student_title" type="text" value="{{student_obj.name}}" required>
                                {% else %}
                                <input id="id_student_title" maxlength="30" name="student_title" type="text" required>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2">
                                Department:
                            </label>
                            <div class="col-sm-10">
                                <select name="student_dept" required>
                                    <option value="">--</option>
                                    {% for dept in dept_objs%}
                                    {% if student_obj %}
                                        {% if dept.dept_id == student_obj.dept_id.dept_id%}
                                        <option value="{{dept.dept_id}}" selected="selected">{{dept.dept_name}}</option>
                                        {% else %}
                                        <option value="{{dept.dept_id}}">{{dept.dept_name}}</option>
                                        {% endif %}
                                    {% else %}
                                        <option value="{{dept.dept_id}}">{{dept.dept_name}}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                {% if student_obj %}
                                <button type="submit" class="btn btn-success">Save student</button>
                                {% else %}
                                <button type="submit" class="btn btn-success">Add student</button>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<a href="{% url 'dean_staff_office:student_catalogue'%}">Back to Student Catalogue</a>
<br>
<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>
</div>

{% endblock %}

dean_staff_office/templates/dean_staff_office/course_catalogue.html
<h3>Course Catalogue</h3>

{% for dept_obj in dept_objs%}
<h3>{{dept_obj.dept_name}}</h3>
{% for depts_course in depts_courses %}
<ul>
	{% for courses in depts_course %}
	{% if courses.dept_id.dept_id == dept_obj.dept_id %}
	<li>{{courses.title}}<a href="/dean_staff_office/edit_course/{{courses.course_id}}">Edit</a></li>
	{% endif %}
	{% endfor %}
</ul>


{% endfor %}
{% endfor %}

<a href="{% url 'dean_staff_office:add_course' %}">Add New Course</a>
<br>
<a href="{% url 'dean_staff_office:home' %}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/faculty_catalogue.html
<h3>Faculty Catalogue</h3>

{% for dept_obj in dept_objs%}
<h3>{{dept_obj.dept_name}}</h3>
<ul>
	{% for facultys in faculty_objs %}
	{% if facultys.dept_id.dept_id == dept_obj.dept_id %}
	<li>{{facultys.faculty_id}}: {{facultys.name}}<a href="/dean_staff_office/edit_faculty/{{facultys.faculty_id}}">Edit</a></li>
	{% endif %}
	{% endfor %}
</ul>


{% endfor %}

<a href="{% url 'dean_staff_office:add_faculty' %}">Add New Faculty</a>
<br>
<a href="{% url 'dean_staff_office:home' %}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/home.html
<h2>Hello {{ staff_obj.staff_name }}</h2>

<a href="{% url 'dean_staff_office:course_catalogue'%}">Course Catalogue</a>
<br>
<a href="{% url 'dean_staff_office:student_catalogue' %}">Student Catalogue</a>
<br>
<a href="{% url 'dean_staff_office:faculty_catalogue' %}">Faculty Catalogue</a>
<br>
<a href = "{% url 'dean_staff_office:update_sem_year_form'%}">Update Academic Year / Sem</a>
<br>
<a href = "{% url 'dean_staff_office:portal_open_close'%}">CRP/Grade Update portals open/close</a>
<br>
<a href="{% url 'dean_staff_office:add_dean' %}">Add/Change Dean</a>
<br>
<a href="{% url 'dean_staff_office:add_hod' %}">Add HOD</a>
<br>
<a href="{% url 'dean_staff_office:add_advisor' %}">Add Advisor</a>
<br>
<br>
<a href="{% url 'dean_staff_office:logout' %}">Logout</a>

dean_staff_office/templates/dean_staff_office/portal_open_close.html
<h2>Portals Open Close Portal</h2>
<br>

 {% if good_message %}
 <p style="color: blue"><strong>{{good_message}}</strong></p>
{% endif %}





<form action="{% url 'dean_staff_office:portals_post'%}" method='post'>
{% csrf_token %}
<div class="form-group">
    <label class="control-label col-sm-2" for="id_crp_open">
        CRP Open:
    </label>
    <div class="col-sm-10">
        <input id="id_crp_open" maxlength="30" name="id_crp_open" type="checkbox" {% if crp_open%} checked {% endif %}>
    </div>
</div>
  
  
<br>
<br>
<div class="form-group">
    <label class="control-label col-sm-2" for="id_grade_open">
        Grade Update Open:
    </label>
    <div class="col-sm-10">
        <input id="id_grade_open" maxlength="30" name="id_grade_open" type="checkbox" {% if grade_update_open%} checked {% endif %}>
    </div>
</div>
<br>
<input type="submit" value="Update Portals">

  </form>


<a href="{% url 'dean_staff_office:home'%}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/student_catalogue.html
<h3>Student Catalogue</h3>

{% for dept_obj in dept_objs%}
<h3>{{dept_obj.dept_name}}</h3>
<ul>
	{% for students in student_objs %}
	{% if students.dept_id.dept_id == dept_obj.dept_id %}
	<li>{{students.student_id}}: {{students.name}}<a href="/dean_staff_office/edit_student/{{students.student_id}}">Edit</a></li>
	{% endif %}
	{% endfor %}
</ul>


{% endfor %}

<a href="{% url 'dean_staff_office:add_student' %}">Add New Student</a>
<br>
<a href="{% url 'dean_staff_office:home' %}">Back to Home</a>

dean_staff_office/templates/dean_staff_office/update_sem_year_form.html

{% block body %}
<h3>Update the Academic year or sem</h3>

<p style="color: red">{{error_message}}</p>
<p style="color: blue">{{good_message}}</p>
<form action="{% url 'dean_staff_office:update_sem_year'%}" method="post">
  {% csrf_token %}

 Fill Academic Year
 <input type="number" name="year">
 <br><br>
 Fill semester (1 or 2)
 <input type="number" name="sem" min="1" max="2">
 <br><br>

<input type="submit" name="Update" value="submit">

</form>
{% endblock %}